### ISSUE TITLE
The function actionPrintText() not work in android 11

### ISSUE THREAD

**Issue by hymith** [star-micronics/StarXpand-SDK-Android#17]
The function actionPrintText() not work in android 11 but actionPrintImage or actionPrintQRCode worked fine!

## Device
 - Device: Google Pixel 2XL (android 11)

## Printer
- Model Names: TSP100IIIL

**Comment by YuzoKato** [comment]
TSP100III series does not support [actionPrintText(content: String)](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10-star-xpand-command/printer-builder/action-print-text.html#android-kotlin-star-xpand-command-printer-builder-action-print-text) because the products are graphics-only printers. Please use the [actionPrintImage(parameter: ImageParameter)](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10-star-xpand-command/printer-builder/action-print-image.html#android-kotlin-star-xpand-command-printer-builder-action-print-image) to create printing data for these products. For other available methods, please also refer to “Supported Model” of each method.

You can refer to [GraphicReceipt sample code](https://github.com/star-micronics/StarXpand-SDK-Android/blob/main/app/src/main/java/com/starmicronics/starxpandsdk/printingsamples/Sample15_GraphicReceipt.kt) about how to create data for graphic printers. You can see the image on [#15 GraphicReceipt 2inch](https://github.com/star-micronics/StarXpand-SDK-Android/blob/main/app/src/main/java/com/starmicronics/starxpandsdk/printingsamples/PrintingSamples.md#15-graphic-receipt---2inch).

**Comment by Tatsuki-Yamamoto2731** [comment]
I am closing this Issue. If you still have this issue, please reopen it.
