### ISSUE TITLE
Is there any way to increase font size without making bold or dark?

### ISSUE THREAD

**Issue by SidSpPlus** [star-micronics/StarXpand-SDK-Android#21]

**Comment by Tatsuki-Yamamoto2731** [comment]
@SidSpPlus You may be able to use [MagnificationParameter](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/android-kotlin-api-reference/stario10-star-xpand-command/magnification-parameter/index.html).

You can refer [this page](https://star-m.jp/products/s_print/sdk/starxpand/manual/en/basic-step1.html#:~:text=Call%20the%20add,the%20character%20string.) for the usage.

Could you please try it?

**Comment by SidSpPlus** [comment]
Any feedback?

**Comment by SidSpPlus** [comment]
@Tatsuki-Yamamoto2731 Any solution for this?

**Comment by SidSpPlus** [comment]
@Tatsuki-Yamamoto2731 Hello

**Comment by Tatsuki-Yamamoto2731** [comment]
@SidSpPlus According to your comment, I think you are using StarPRNT SDK (here is StarXpand SDK issue).
Unfortunately, appendMultiple() cannot increase font size without making it bold or dark. This is because if the width is doubled, the letter thickness is also doubled.

If you must increase font size without making it bold or dark, the only way is to make printing data as an image (graphic) and use appendBitmap().

**Comment by SidSpPlus** [comment]
@Tatsuki-Yamamoto2731 Thank you.
