### ISSUE TITLE
com.starmicronics.stario 10.stario 10 invalidoperationexception not opened error code none in kotlin

### ISSUE THREAD

**Issue by abhishekcitytech** [star-micronics/StarXpand-SDK-Android#24]
After discovery succesful of my Star printer model , my android app occuring below error.                                                                             com.starmicronics.stario 10.stario 10 invalidoperationexception not opened error code none in kotlin. Kindly help me o

**Comment by bandit-ibayashi** [comment]
@abhishekcitytech Sorry for our late response.
And from your information, I have transferred this issue moved to a repository deemed appropriate.

Could you provide the necessary information using the following template and filling that in?

----
## Description
A clear and concise description of what a bug is.

## Your device where the bug occurs 
 - Device: 
    *e.g. iPhone 13*
 - OS:
    *e.g. iOS 15.0*
 - Browser: 
    *e.g. Safari*
 - Version
    *e.g. 22*

## Your printer
- Model Names:
    *e.g. mC-Print3*
- Firmware Version:
    *e.g. 3.5*
- Interface:
    *e.g. Ethernet*

## Your development environment
The result of executing the command `ver` on Windows, `sw_vers` on macOS, `uname –a` on Linux, or these equivalent commands.

## To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

## Expected behavior
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Additional context
Add any other context about the bug here.
----

Thank you in advance.

**Comment by Tatsuki-Yamamoto2731** [comment]
Not updated for more than 3 months, therefore I closed this issue. If you still have the same issue, please reopen this issue.
